general:
  productiveBranch: 'piper'
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder:latest'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'pipertest'
      space: 'pipertestspace'
  influxWriteData:
   influxServer: 'jenkins'
