general:
  buildTool: mta
  productiveBranch: piperPipeline
stages:
  'Additional Unit Tests':
    karmaExecuteTests: true
  'Release':
    cloudFoundryDeploy: true
steps:
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'pipertest'
      space: 'pipertestspace'
  karmaExecuteTests:
    modules: ['./MySampleApp']
    runCommand: 'npm run karma-ci'
  influxWriteData:
   influxServer: 'jenkins'
