general:
  buildTool: mta
  productiveBranch: piperPipeline
  verbose: true
stages:
  'Additional Unit Tests':
    karmaExecuteTests: true
  'Release':
    cloudFoundryDeploy: true
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder:latest'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'pipertest'
      space: 'pipertestspace'
  karmaExecuteTests:
    modules: ['./MySampleApp']
    runCommand: 'npm run karma-ci'
  artifactSetVersion:
    commitVersion: false
  influxWriteData:
   influxServer: 'jenkins'
