steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'radsoulbeard/agnosticmta:latest'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'pipertest'
      space: 'pipertestspace'
  karmaExecute:
    modules: ['./MySampleApp']
    runCommand: npm run test
  influxWriteData:
   influxServer: 'http://localhost:8086'
