steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder:latest:latest'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'pipertest'
      space: 'pipertestspace'
  karmaExecuteTests:
    modules: ['./MySampleApp']
    runCommand: npm run test
  influxWriteData:
   influxServer: 'jenkins'
